const ProductsFourthList = [
    {
      id: 1,
      name: "Gymreapers Lifting Straps | Premium Padded Weightlifting Straps",
      price: "Rs. 1,300.00",
      rating: 4.9,
      hoverImg: "/GearImage/black-white-lifting-straps-both-wrapped.jpg",
      initialImg: "/GearImage/lifting-straps-black-white-OG.jpg",
      colors: [ 
        "/GearImage/lifting-straps-black-white-OG.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        
        { size: "XS (24-31\")"},
        { size: "S (26-33\")"},
        { size: "M (30-36\")"},
        { size: "L (34-41\")"},
        { size: "XL (38-45\")"},
        { size: "2XL (39-46\")"},
      ],
    },
    {
      id: 2,
      name: "Gymreapers Wrist Wraps - 18 Weightlifting Wrist Support",
      price: "Rs.1800.00",
      rating: 5.9,
      initialImg:"/GearImage/wrist-wraps-black-main_800x.jpg",
      hoverImg:  "/GearImage/wrist-wraps-black-single.jpg",
  
      colors: [ 
        "/GearImage/wrist-wraps-black-main_800x.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    },
    {
      id: 3,
      name: "Gymreapers Lifting Hooks - Black",
      price: "Rs. 2,700.00",  
      rating: 5.9,
      hoverImg: "/GearImage/lifting-hooks-black-full.jpg",
      initialImg: "/GearImage/lifting-hooks-black-side.jpg",
      colors: [ 
        "/GearImage/lifting-hooks-black-side.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    }, {
      id: 4,
      name: "Gymreapers Lifting Grips",
      price: "Rs. 3,500.00",
      rating: 5.9,
      hoverImg: "/GearImage/lifting-grips-black-half-folded.jpg",
      initialImg: "/GearImage/lifting-grips-black-main.jpg",
      colors: [ 
        "/GearImage/lifting-grips-black-main.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    }, {
      id: 5,
      name: "7MM Knee Sleeves - Black/Black",
      price: "Rs. 5,300.00",
      rating: 5.9,
      hoverImg: "/GearImage/Knee-Sleeve-Black-Black-side-by-side_efc37093-5a6f-4b58-ae38-da47bf68f168.jpg",
      initialImg: "/GearImage/Knee-Sleeve-Black-Black-Front-Back_b46c055f-c4d0-4cfa-812c-dd407a85e5cc.jpg",
      colors: [ 
        "/GearImage/Knee-Sleeve-Black-Black-Front-Back_b46c055f-c4d0-4cfa-812c-dd407a85e5cc.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    }, {
      id: 6,
      name: "Gymreapers 5MM Elbow Sleeves | Weightlifting Elbow Support",
      price: "Rs. 3,500.00",
      rating: 5.9,
      hoverImg:"/GearImage/5mm-elbow-sleeves-black-white-front-back.jpg",
      initialImg: "/GearImage/7mm-knee-sleeves-black-white-main.jpg",
      colors: [ 
        "/GearImage/7mm-knee-sleeves-black-white-main.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    }, 
    {
      id: 7,
      name: "Gymreapers Knee Wraps - Black",
      price: "Rs. 2,700.00",
      rating: 5.9,
      hoverImg: "/GearImage/knee-wrap-black-main.jpg",
      initialImg: "/GearImage/knee-wrap-black-main.jpg",
      colors: [ 
        "/GearImage/knee-wrap-black-main.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    },
    {
      id: 8,
      name: "Gymreapers Elbow Wraps",
      price: "Rs. 2,700.00",
      rating: 5.9,
      hoverImg: "/GearImage/ElbowWrap_Black_1_New.jpg",
      initialImg: "/GearImage/ElbowWrap_Black_1_New.jpg",
      colors: [ 
        "/GearImage/ElbowWrap_Black_1_New.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    },
   
  ];
export default ProductsFourthList