const ProductsThreeList = [
    {
      id: 1,
      name: "Cropped Zip-Up Hoodie - Black",
    badge: "New Release",
      price: "Rs.5,700.00",
      rating: 4.9,
      hoverImg: "/WomenAppral/black-white-cropped-hoodie-back-detail.jpg",
      initialImg: "/WomenAppral/black-white-cropped-hoodie-main.jpg",
      colors: [ 
        "/WomenAppral/black-white-cropped-hoodie-main.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")"},
        { size: "S (26-33\")"},
        { size: "M (30-36\")"},
        { size: "L (34-41\")"},
        { size: "XL (38-45\")"},
        { size: "2XL (39-46\")"},
      ],
    },
    {
      id: 2,
      name: "Women's Performance Running Jacket",
    badge: "New Release",
      price: "Rs.5700",
      rating: 5.9,
      initialImg:"/WomenAppral/Black-Performance-running-jacket-main.jpg",
      hoverImg:  "/WomenAppral/black-performance-running-jacket-back.jpg",
  
      colors: [ 
        "/WomenAppral/Black-Performance-running-jacket-main.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    },
    {
      id: 3,
      name: "Women's Performance Quarter Zip",
    badge: "New Release",
      price: "Rs. 5,700.00",
      rating: 5.9,
      hoverImg: "/WomenAppral/womens-performance-1-4-zip-black-back.jpg",
      initialImg: "/WomenAppral/womens-performance-1-4-zip-black-front.jpg",
      colors: [ 
        "/WomenAppral/womens-performance-1-4-zip-black-front.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    }, {
      id: 4,
      name: "40MM Lever Belt - Black",
      price: "Rs. 3,500.00",
    badge: "New Release",
      rating: 5.9,
      hoverImg: "/WomenAppral/infinity-leggings-black-back.png",
      initialImg: "/WomenAppral/infinity-leggings-black-main-image.jpg",
      colors: [ 
        "/WomenAppral/infinity-leggings-black-main-image.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    }, {
      id: 5,
      name: "Infinity Shorts 3-Packs",
    badge: "Lifetime Warranty",
      price: "Rs. 7,000.00",
      rating: 5.9,
      hoverImg: "/WomenAppral/emerald-infinity-shorts-front-full-shot-studio_81af8b5c-183b-4e8d-bca5-d29666c54333.jpg",
      initialImg: "/WomenAppral/shorts-3-pack-azure-miami-emerald2.png",
      colors: [ 
        "/WomenAppral/shorts-3-pack-azure-miami-emerald2.png",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    }, {
      id: 6,
      name: "Infinity Shorts - Black",
    badge: "Lifetime Warranty",
      price: "Rs. 2,600.00",
      rating: 5.9,
      hoverImg:"/MenAppral/training-shorts-black-front.jpg",
      initialImg: "/MenAppral/gr-training-shorts-3-pack-red-blu-blk_1024.jpg",
      colors: [ 
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    }, {
      id: 7,
      name: "Legacy Shorts - Black",
    badge: "Lifetime Warranty",
      price: "Rs. 3,700.00",
      rating: 5.9,
      hoverImg: "/MenAppral/training-shorts-black-back (1).jpg",
      initialImg: "/MenAppral/training-shorts-black-front.jpg",
      colors: [ 
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    },
    {
      id: 8,
      name: "Victory Shorts - Black",
    badge: "Lifetime Warranty",
      price: "priceRs. 3,100.00",
      rating: 5.9,
      hoverImg: "/MenAppral/training-shorts-black-back (1).jpg",
      initialImg: "/MenAppral/Black-min.jpg",
      colors: [ 
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
        "/ProductPage/gravestone_backpack_lever_green.jpg",
        "/ProductPage/gravestone_backpack_lever2.jpg",
      ],
      sizes: [
        { size: "XS (24-31\")", price: "24,900.00" },
        { size: "S (26-33\")", price: "24,500.00" },
        { size: "M (30-36\")", price: "24,800.00" },
        { size: "L (34-41\")", price: "25,000.00" },
        { size: "XL (38-45\")", price: "25,300.00" },
        { size: "2XL (39-46\")", price: "25,500.00" },
      ],
    },
  ];
export default ProductsThreeList